Added top tole property to member
nekokatt/hikari pull request #129
Opened 2020-09-07 06:26 UTC by ahnaf-zamil

### Summary

### Checklist

- [ ] I have run `nox` and all the pipelines have passed.
- [x] I have tested the code with a sample bot and everything is working without errors.

### Related issues
This doesn't work stateless without cache. This is why the nox tests couldn't be passed. Also I don't know how to write tests. So I need someone to check the code and see if it has issues.

2020-09-07 06:45 UTC, davfsa requested changes
Several things and you will have to make it take into account a missing intents cache and a stateless bot (which will return a EmptyCacheView) and return `None` instead of a role. Also, always remember to run `nox` before you commit to make sure all pipelines will pass

2020-09-07 06:45 UTC, davfsa commented on hikari/guilds.py
> +        return max(
Please run black `nox -s black` to fix this as the linter is complaning

2020-09-07 06:45 UTC, davfsa commented on tests/hikari/test_guilds.py
> +        assert obj.top_role.guild_id == "Owner"
This is not the right way of testing this. You will have to mock `app.cache.get_roles_view_for_guild`, make it return a dict with the values you expect, make sure it gets called with the right guild_id and that the role return is the correct one. You will also have to write tests (and modify the code you wrote) for when an empty role view is returned (missing intents so we didnt cache it or he is using a stateless bot).

2020-09-07 07:24 UTC, nekokatt commented
You are getting the hang of how these components slot together, just a couple of points that I'd like to see fixed from me and Dav, if that is okay?

Thanks for spending the time to do this, it is greatly appreciated :-)

2020-09-08 13:14 UTC, nekokatt requested changes

2020-09-09 09:55 UTC, ahnaf-zamil commented
> 
> 
> You are getting the hang of how these components slot together, just a couple of points that I'd like to see fixed from me and Dav, if that is okay?
> 
> Thanks for spending the time to do this, it is greatly appreciated :-)

Thanks, I just tried to do something to help. I am not very familiar with caching and testing in general so it's kinda hard for me to contribute to this project.

2020-09-10 01:07 UTC, nekokatt commented
> > You are getting the hang of how these components slot together, just a couple of points that I'd like to see fixed from me and Dav, if that is okay?
> > Thanks for spending the time to do this, it is greatly appreciated :-)
> 
> Thanks, I just tried to do something to help. I am not very familiar with caching and testing in general so it's kinda hard for me to contribute to this project.

if you want any help, ping one of us :+1:

2020-09-11 08:51 UTC, davfsa commented on tests/hikari/test_guilds.py
> +                top_role=mock.Mock(return_value="Owner"),
Dont mock something you are testing ;)

2020-09-12 10:40 UTC, closed without merging