avoid the shard ratelimits slowing down event dispatch
nekokatt/hikari pull request #134
Opened 2020-09-07 21:33 UTC by FasterSpeeding

### Summary
shard.request_guild_members in places to avoid it blocking other stuff unnecessarily.

### Checklist

- [x ] I have run `nox` and all the pipelines have passed.
- [ x] I have made unittests according to the code I have added/modified/deleted.

### Related issues

2020-09-07 21:34 UTC, nekokatt requested changes

2020-09-07 21:34 UTC, nekokatt commented on hikari/impl/stateful_event_manager.py
> +            asyncio.create_task(shard.request_guild_members(event.guild))
can we give this a name

2020-09-07 21:35 UTC, FasterSpeeding reviewed
Wanted to have similar behaviour in StatefulGuildChunkerImpl.request_guild_members where we don't wait for the request to go through but here we have to ensure any errors from the validation are raised and while we could do something like the following
```python
finished_coroutines, _ asyncio.wait((asyncio.create_task(shard.request_guild_members())), timeout=1)
if finished_coroutines:
    await finished_coroutines[0]
```
this feels jank so not sure if that should be included or not

2020-09-07 22:01 UTC, FasterSpeeding commented on hikari/impl/stateful_event_manager.py
> +            asyncio.create_task(shard.request_guild_members(event.guild))
done

2020-09-08 07:44 UTC, nekokatt approved these changes

2020-09-08 07:44 UTC, merged