Allow Color.of to accept string representation of an RGB Tuple
nekokatt/hikari pull request #177
Opened 2020-09-13 13:42 UTC by tandemdude

### Summary
Allows Color.of to accept string representations of RGB tuples, eg: `(0, 0, 0)` or `0, 0, 0`. This also works for float RGB values.

### Checklist

- [x] I have run `nox` and all the pipelines have passed.
- [ ] I have made unittests according to the code I have added/modified/deleted.

### Related issues

2020-09-13 21:43 UTC, nekokatt commented
Big ask, but can we amend the tests with the link i sent earlier from v1?

Also build is failing, so you might want to check that.

2020-09-14 07:04 UTC, davfsa reviewed
Just the tests as what nekokatt said, but LGTM

2020-09-14 13:21 UTC, davfsa approved these changes
LGTM

2020-09-14 16:53 UTC, nekokatt requested changes
Tests.

2020-09-15 07:51 UTC, nekokatt approved these changes

2020-09-15 07:52 UTC, davfsa approved these changes
LGTM

2020-09-15 07:56 UTC, merged